---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongodb-backup-sa-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage.admin  # Or create a custom role with just the permissions you need
subjects:
- kind: ServiceAccount
  name: mongodb-backup-sa
  namespace: default  # Change to your namespace